branch-defaults:
  default:
    environment: StreamSniper-env
environment-defaults:
  StreamSniper-env:
    branch: null
    repository: null
deploy:
  artifact: Dockerrun.aws.json
global:
  application_name: stream-sniper
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
